# config/packages/framework.yaml

framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    session: true
    # error_controller: 'App\Controller\ExceptionController::showAccessDenied'

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
